### ISSUE TITLE
CRITICAL Uncaught Error in icepay.php

### ISSUE THREAD

**Issue by Croolw** [ICEPAY/WooCommerce#10]
Hi , i am getting this error, can you help me out?
i am using  WC Version: 5.2.1
Icepay: Version: 2.3.9

2019-05-29T14:20:50+00:00 CRITICAL Uncaught Error: Call to a member function get_billing_country() on null in /wp-content/plugins/icepay-woocommerce-online-payment-module/icepay.php:384
Stack trace:
#0 /wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(151): ICEPAY_Paymentmethod_Core->is_available()
#1 /wp-content/plugins/woocommerce/includes/wc-account-functions.php(118): WC_Payment_Gateways->get_available_payment_gateways()
#2 /wp-content/plugins/woocommerce/includes/admin/class-wc-admin-menus.php(291): wc_get_account_menu_items()
#3 /wp-admin/includes/template.php(1430): WC_Admin_Menus->nav_menu_links(NULL, Array)
#4 wp-admin/nav-menus.php(853): do_accordion_sections(Object(WP_Screen), 'side', NULL)
#5 {main}
  thrown in /wp-content/plugins/icepay-woocommerce-online-payment-module/icepay.php op de lijn 384

The line 384 is:  **->filterByCountry(WC()->customer->get_billing_country())**

**Comment by Twansparant** [comment]
Same here! Did you find a workaround for this by any chance?
Thanks!

**Comment by Croolw** [comment]
Hi Twan, 
i changed this function and now it is working fine:
 public function is_available()
        {
            global $wpdb;
            $allPaymentMethods = $wpdb->get_var("SELECT raw_pm_data FROM `{$this->getTableWithPrefix('woocommerce_icepay_pmrawdata')}`");
            if ($allPaymentMethods == null) {
                return false;
            }
            $allPaymentMethods = unserialize($allPaymentMethods);
	    if(is_Admin()){
		    $contry='NL';
	    } else {
		    $contry=WC()->customer->get_billing_country();
		    if($contry==''){
		        $contry='NL';
		    }
	    }	
            //echo '<div class="hide" style="display:none">';var_dump($contry);echo '</div>';
	    $filter = Icepay_Api_Webservice::getInstance()->filtering();
            $filter->loadFromArray($allPaymentMethods);
            $filter->filterByCurrency(get_woocommerce_currency())
                ->filterByCountry($contry)
                ->filterByAmount((int)$this->get_order_total() * 100);
            $this->filteredPaymentMethods = $filter->getFilteredPaymentmethods();
            if (!$filter->isPaymentMethodAvailable($this->paymentMethodCode)) {
                return false;
            }
            return parent::is_available();
        }
