### ISSUE TITLE
error icepay with woocommerce.

### ISSUE THREAD

**Issue by dezechinees** [ICEPAY/WooCommerce#7]
Hi,
Hope you can help with this issue. icepay plugin for woocommerce is causing following error:

2018-10-25T11:04:22+00:00 CRITICAL require(): Failed opening required '/home/public/sites/www.curvyladys.nl/wp-content/plugins/WooCommerce-master//api/src/icepay_api_webservice.php' (include_path='.:/usr/share/php') in /home/public/sites/www.curvyladys.nl/wp-content/plugins/WooCommerce-master/icepay.php op de lijn 25

version woocommerce 3.5.1
version wordpress 4.9.8

Let me know if more info is needed.

Regards.

**Comment by dezechinees** [comment]
Also when i debug i get this message:


Fatal error: Uncaught Error: Class 'ICEPAY_PaymentMethod_15' not found in /home/public/sites/www.curvyladys.nl/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php:108 Stack trace: #0 /home/public/sites/www.curvyladys.nl/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(70): WC_Payment_Gateways->init() #1 /home/public/sites/www.curvyladys.nl/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(43): WC_Payment_Gateways->__construct() #2 /home/public/sites/www.curvyladys.nl/wp-content/plugins/woocommerce/includes/class-woocommerce.php(687): WC_Payment_Gateways::instance() #3 /home/public/sites/www.curvyladys.nl/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-menus.php(90): WooCommerce->payment_gateways() #4 /home/public/sites/www.curvyladys.nl/wp-includes/class-wp-hook.php(286): WC_Admin_Menus->settings_page_init('') #5 /home/public/sites/www.curvyladys.nl/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #6 /home/public/sites/www.curvyla in /home/public/sites/www.curvyladys.nl/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php on line 108

**Comment by tsygankov** [comment]
Hi,

Please get the latest (2.3.9) version of the module from the 'develop' branch.

I will publish a stable release in few hours.

**Comment by tsygankov** [comment]
Done! Please try installing the [latest](https://github.com/ICEPAY/WooCommerce/releases/tag/2.3.9) version.
